### ISSUE TITLE
Could not pass event PlayerTeleportEvent to FlectoneChat v3.0

### ISSUE THREAD

**Issue by mindlss** [Flectone/FlectoneChat#1]
Hello there! i keep getting:

```
java.lang.NullPointerException: Cannot invoke "ru.flectonechat.Tools.FlectonePlayer.setWorldColor(org.bukkit.World)" because the return value of "java.util.HashMap.get(Object)" is null
        at ru.flectonechat.Tools.Utils.UtilsMain.useSetWorldColor(UtilsMain.java:75) ~[FlectoneChat.jar:?]
        at ru.flectonechat.PlayerActions.WorldChange.playerTeleport(WorldChange.java:27) ~[FlectoneChat.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1564]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1702) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1673) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1669) ~[?:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:344) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:564) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1674) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
when player connects to the server.

**Comment by TheFaser** [comment]
Hello. I'm sorry that plugin was not supported. At the moment I took up his work and completely rewrote it. I gained experience and now I have an idea about normal code :)
