### ISSUE TITLE
AsyncPlayerChatEvent error

### ISSUE THREAD

**Issue by Dimersion32** [Flectone/FlectoneChat#26]
[21:31:10 ERROR]: Could not pass event AsyncPlayerChatEvent to FlectoneChat v4.4.0
org.bukkit.event.EventException: null
at net.flectone.chat.module.FListener.lambda$registerEvents$0(FListener.java:71) ~[FlectoneChat-4.4.0.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.1.jar:git-Purpur-2062]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[purpur-1.20.1.jar:git-Purpur-2062]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2553) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2682) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$19(ServerGamePacketListenerImpl.java:2381) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]

Caused by: java.lang.NullPointerException: Cannot invoke "net.flectone.chat.model.player.Settings.getChat()" because the return value of "net.flectone.chat.model.player.FPlayer.getSettings()" is null
at net.flectone.chat.module.playerMessage.chat.ChatListener.playerChatEvent(ChatListener.java:46) ~[FlectoneChat-4.4.0.jar:?]
at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
at net.flectone.chat.module.FListener.lambda$registerEvents$0(FListener.java:69) ~[FlectoneChat-4.4.0.jar:?]
... 15 more

Plugin version: FlectoneChat 4.4.0
Server version: 1.20.1 purpur
Plugins: GSit , LuckPerms-Bukkit , NametagEdit , OpenLogin , PlaceholiderAPI , UltimateAutoRestart , Vault , FlectoneChat
Server properties file:
[server.properties.txt](https://github.com/Flectone/FlectoneChat/files/13697471/server.properties.txt)

**Comment by TheFaser** [comment]
This error is a consequence of another error. Are there any errors in the console before this? It may have occurred when a player logs in

**Comment by Dimersion32** [comment]
> Эта ошибка является следствием другой ошибки. Есть ли ошибки в консоли до этого? Это могло произойти, когда игрок вошел в игру

Да, сейчас посмотрю. (Увидел, что в других Issues обсуждают на русском)

**Comment by Dimersion32** [comment]
[latestserver.log.txt](https://github.com/Flectone/FlectoneChat/files/13697486/latestserver.log.txt)

Вот полные логи. Сейчас смотрю их. Возможно вы увидите что-то, что не вижу я.

**Comment by TheFaser** [comment]
Ну первое, что я увидел, это флектончат жалуется, что ты удалил server-icon-1.png и server-icon-2.png из icons. Либо можешь их вернуть, либо в конфиге отключить иконки и их отображение
![image](https://github.com/Flectone/FlectoneChat/assets/69783345/1c620a03-7340-46a8-a0fb-bbc16228ed2c)

**Comment by TheFaser** [comment]
А нет, я ошибаюсь, это связано с тем, что размер иконки у тебя слишком большой 512x512, а максимальный это 64x64

**Comment by Dimersion32** [comment]
> Ну первое, что я увидел, это флектончат жалуется, что ты удалил server-icon-1.png и server-icon-2.png из icons. Либо можешь их вернуть, либо в конфиге отключить иконки и их отображение ![image](https://private-user-images.githubusercontent.com/69783345/291098068-1c620a03-7340-46a8-a0fb-bbc16228ed2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDA1ODYsIm5iZiI6MTcwMjg0MDI4NiwicGF0aCI6Ii82OTc4MzM0NS8yOTEwOTgwNjgtMWM2MjBhMDMtNzM0MC00NmE4LWEwZmItYmJjMTYyMjhlZDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5MTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmNhMmNmZmZiYWQyNjM0OWI4OGZlNDgzZjFhOWI4ZTllM2JkZjZjYTkxZWNhNjgyNWQ4ZmYxZGZjYjUwMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0puIU60NPQS2gRuFJMD_EbVB9WKxtnpgD3WR30TnssU)

Да, тоже это видел, но не обращал внимания. Это связано с ошибкой чата?

**Comment by TheFaser** [comment]
Скорее всего это связано с этим, не уверен. Попробуй решить проблему (выключить кастомные иконки во флектончате или уменьши размер иконки до 64x64) и чекнуть, всё ли нормально

**Comment by TheFaser** [comment]
> А нет, я ошибаюсь, это связано с тем, что размер иконки у тебя слишком большой 512x512, а максимальный это 64x64

Получается не особо ошибся я, у тебя одна иконка слишком большая, а другой попросту нет (ты её скорее всего сам удалил из icons)
![image](https://github.com/Flectone/FlectoneChat/assets/69783345/535a9d17-668d-4fe8-96ab-f0b07b590b38)

Если не хочешь режим переключения иконок, то можешь из списка удалить иконку вторую
![image](https://github.com/Flectone/FlectoneChat/assets/69783345/20bd2140-ad32-4960-afa3-4882093d713f)

**Comment by Dimersion32** [comment]
> > А нет, я ошибаюсь, это связано с тем, что размер иконки у тебя слишком большой 512x512, а максимальный это 64x64
> 
> Получается не особо ошибся я, у тебя одна иконка слишком большая, а другой попросту нет (ты её скорее всего сам удалил из icons) ![image](https://private-user-images.githubusercontent.com/69783345/291098335-535a9d17-668d-4fe8-96ab-f0b07b590b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDA5MDgsIm5iZiI6MTcwMjg0MDYwOCwicGF0aCI6Ii82OTc4MzM0NS8yOTEwOTgzMzUtNTM1YTlkMTctNjY4ZC00ZmU4LTk2YWItZjBiMDdiNTkwYjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5MTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2M2MwMzRkNDg4NjJjNjNjNDA4ZmYwNzVlY2M0MDJjOTZhZDBmZWI4ZjgxYzIzN2I0MmU1ZDZhZmJhNzM0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnpE85JbhoK35s8RTVgMHzUmuqLNe5tHjUiTzshFpQ4)
> 
> Если не хочешь режим переключения иконок, то можешь из списка удалить иконку вторую ![image](https://private-user-images.githubusercontent.com/69783345/291098405-20bd2140-ad32-4960-afa3-4882093d713f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDA5MDgsIm5iZiI6MTcwMjg0MDYwOCwicGF0aCI6Ii82OTc4MzM0NS8yOTEwOTg0MDUtMjBiZDIxNDAtYWQzMi00OTYwLWFmYTMtNDg4MjA5M2Q3MTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE5MTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjE4OTNmZGJjNmZmMWMwMDcxZmVjM2U2Y2VhMDRkZmE4M2FiNGM2YWIzYjc0OGRlMTdlNTkwODk0MDc1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yM_7DrL76qY7HqVsxEXyRYYo7wksJ6KWazjcMbwlFng)

Спасибо большое, я сделал немного не так, так как не разобрался. Исправил вроде, тестирую...

**Comment by TheFaser** [comment]
У нас есть вики, где очень много информации объяснено, по поводу конфигурации плагина
https://chat.flectone.net/docs/

Если возникнут следующие проблемы/вопросы, можешь их писать в наш дискорд
https://discord.flectone.net/

**Comment by TheFaser** [comment]
Думаю проблема решена
