### ISSUE TITLE
Несовместимость с PlasmoVoice v1

### ISSUE THREAD

**Issue by Kolyakot33** [Flectone/FlectoneChat#28]
Аддоны добавили в PlasmoVoice 2.0, а он есть только под 1.19+. Соответственно на серверах с плазмой для версий ниже этот плагин на чат работать не будет. Хотя это можно отключить, я думаю стоит добавить проверку на версию плазмы.

```[22:56:35 INFO]: [FlectoneChat] Enabling FlectoneChat v4.5.1
[22:56:35 INFO]: [FlectoneChat] SQLite DB Connected successfully
[22:56:35 ERROR]: Error occurred while enabling FlectoneChat v4.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: su/plo/voice/api/addon/AddonInitializer
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:197) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.flectone.chat.module.integrations.IntegrationsModule.init(IntegrationsModule.java:61) ~[FlectoneChat-4.5.1.jar:?]
        at net.flectone.chat.module.integrations.IntegrationsModule.<init>(IntegrationsModule.java:29) ~[FlectoneChat-4.5.1.jar:?]
        at net.flectone.chat.manager.FModuleManager.init(FModuleManager.java:42) ~[FlectoneChat-4.5.1.jar:?]
        at net.flectone.chat.FlectoneChat.onEnable(FlectoneChat.java:61) ~[FlectoneChat-4.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.plo.voice.api.addon.AddonInitializer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 23 more
[22:56:35 INFO]: [FlectoneChat] Disabling FlectoneChat v4.5.1
```

**Comment by TheFaser** [comment]
Это больше проблемы плазмы, что их нету на 1.16.5, хотя я не уверен в этом, думаю на их гитхабе должно быть. Проверяться такое не будет, просто выключи внутри integrations.yml
