### ISSUE TITLE
Ошибка подгрузки иконки

### ISSUE THREAD

**Issue by SoursXond** [Flectone/FlectoneChat#29]
Проверял без плагинов на spigot 1.20.4

```
[09:29:45] [Netty Server IO #2/WARN]: [FlectoneChat] Unable to load and install server-icon-6.png image
[09:29:45] [Netty Server IO #2/WARN]: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "bufferedImage" is null
[09:29:45] [Netty Server IO #2/WARN]:   at net.flectone.chat.module.server.status.StatusListener.setIcon(StatusListener.java:82)
[09:29:45] [Netty Server IO #2/WARN]:   at net.flectone.chat.module.server.status.StatusListener.statusEvent(StatusListener.java:56)
[09:29:45] [Netty Server IO #2/WARN]:   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[09:29:45] [Netty Server IO #2/WARN]:   at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[09:29:45] [Netty Server IO #2/WARN]:   at net.flectone.chat.module.FListener.lambda$registerEvents$0(FListener.java:69)
[09:29:45] [Netty Server IO #2/WARN]:   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:29:45] [Netty Server IO #2/WARN]:   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[09:29:45] [Netty Server IO #2/WARN]:   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.server.network.PacketStatusListener.a(PacketStatusListener.java:122)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.network.protocol.status.PacketStatusInStart.a(SourceFile:19)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.network.protocol.status.PacketStatusInStart.a(SourceFile:6)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.network.NetworkManager.a(NetworkManager.java:207)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.network.NetworkManager.a(NetworkManager.java:189)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:1)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:73)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[09:29:45] [Netty Server IO #2/WARN]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:29:45] [Netty Server IO #2/WARN]:   at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by TheFaser** [comment]
Думаю проблему ты решил, раз закрыл ветку, но в итоге скажу, что дело в server-icon-6.png, её не существует
